apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubirch-protocol-adapter
  namespace: prometheus
  labels:
    app: ubirch-protocol-adapter
    release: prometheus-operator
spec:
  endpoints:
  - interval: 30s
    path: /
    port: prometheus-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    name: "event-log-service"
