apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-log-kafka-lookup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "event-log-kafka-lookup.name" . }}
    helm.sh/chart: {{ include "event-log-kafka-lookup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.eventLogLookup.replicaCount }}
{{- if .Values.eventLogLookup.strategy }}
  strategy:
{{ with .Values.eventLogLookup.strategy }}
{{ toYaml . | indent 4 }}
{{ end }}
{{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-log-kafka-lookup.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "event-log-kafka-lookup.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 9010
            - containerPort: 9020
            - containerPort: 4321
          readinessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 20
            periodSeconds: 60
          env:
            - name: LU_CS_KEYSPACE
              value: "{{ .Values.eventLogLookup.cassandra.cluster.keyspace}}"
            - name: LU_CS_PREPSTM_CACHE
              value: "{{ .Values.eventLogLookup.cassandra.cluster.preparedStatementCacheSize}}"
            - name: LU_CS_NODES
              value: "{{ .Values.eventLogLookup.cassandra.cluster.contactPoints}}"
            - name: LU_CS_CONSISTENCY_LEVEL
              value: "{{ .Values.eventLogLookup.cassandra.cluster.consistencyLevel}}"
            - name: LU_CS_SERIAL_CONSISTENCY_LEVEL
              value: "{{ .Values.eventLogLookup.cassandra.cluster.serialConsistencyLevel}}"
            - name: LU_CS_USERNAME
              value: "{{ .Values.eventLogLookup.cassandra.cluster.username}}"
            - name: LU_CS_PASSWORD
              value: "{{ .Values.eventLogLookup.cassandra.cluster.password}}"
            - name: LU_CS_WITH_SSL
              value: "{{ .Values.eventLogLookup.cassandra.cluster.withSsl}}"
            - name: LU_KFC_NODES
              value: "{{ .Values.eventLogLookup.kafka.bootstrapServers}}"
            - name: LU_KFC_TOPIC
              value: "{{ .Values.eventLogLookup.kafka.consumer.topic}}"
            - name: LU_KFC_GROUP
              value: "{{ .Values.eventLogLookup.kafka.consumer.group}}"
            - name: LU_KFC_MAX_POLL_RECORDS
              value: "{{ .Values.eventLogLookup.kafka.consumer.maxpoll}}"
            - name: LU_KFP_NODES
              value: "{{ .Values.eventLogLookup.kafka.bootstrapServers}}"
            - name: LU_KFP_TOPIC
              value: "{{ .Values.eventLogLookup.kafka.producer.topic}}"
            - name: LU_KFP_ERROR_TOPIC
              value: "{{ .Values.eventLogLookup.kafka.producer.errorTopic}}"
            - name: LU_PROM_HTTP_PORT
              value: "{{ .Values.eventLogLookup.prometheus.port}}"
            - name: EVTL_JAVA_OPTS
              value: "{{ .Values.eventLogLookup.javaopts}}"
            - name: LU_KFP_LINGER_MS
              value: "{{ .Values.eventLogLookup.kafka.producer.linger }}"
            - name: LU_EXEC_THREAD_POOL_SIZE
              value: "{{ .Values.eventLogLookup.exec.threadpoolsize }}"
            - name: LU_KFC_FETCH_MAX_BYTES_CONFIG
              value: "{{ .Values.eventLogLookup.kafka.consumer.fetchMaxBytes }}"
            - name: LU_KFC_MAX_PARTITION_FETCH_BYTES_CONFIG
              value: "{{ .Values.eventLogLookup.kafka.consumer.partitionFetchMaxBytes }}"
            - name: LU_GRM_HOSTS
              value: "{{ .Values.eventLogLookup.gremlin.hosts }}"
            - name: LU_GRM_PORT
              value: "{{ .Values.eventLogLookup.gremlin.port }}"
            - name: LU_GRM_COONPOOL_RECONINTERVAL
              value: "{{ .Values.eventLogLookup.gremlin.connectionPool.reconnectInterval }}"
            - name: LU_GRM_COONPOOL_MAXWAITCONNECTION
              value: "{{ .Values.eventLogLookup.gremlin.connectionPool.maxWaitForConnection }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
