apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-log-chainer
  labels:
    app: event-log-chainer
    release: prometheus-operator
spec:
  endpoints:
  - interval: 30s
    path: /
    port: prometheus-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-log-chainer.name" . }}
      helm.sh/chart: {{ include "event-log-chainer.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
