apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-log-chainer
  namespace: prometheus
  labels:
    app: event-log-chainer
    release: prometheus-operator
spec:
  endpoints:
  - interval: 30s
    path: /
    port: prometheus-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    name: "event-log-chainer"
