package com.ubirch.models

object Values {

  val MASTER_TREE_CATEGORY = "MASTER_TREE"
  val SLAVE_TREE_CATEGORY = "SLAVE_TREE"
  val UPP_CATEGORY = "UPP"
  val CHAIN_CATEGORY = "CHAIN"
  val DEVICE_CATEGORY = "DEVICE"
  val PUBLIC_CHAIN_CATEGORY = "PUBLIC_CHAIN"
  val UNKNOWN_CATEGORY = "UNKNOW_CATEGORY"
  val MASTER_TREE_ID = "master-tree-id"
  val SLAVE_TREE_ID = "slave-tree-id"
  val SLAVE_TREE_LINK_ID = "slave-tree-link-id"
  val SLAVE_TREE_UPGRADE_ID = "slave-tree-upgrade-id"
  val MASTER_TREE_UPGRADE_ID = "master-tree-upgrade-id"
  val MASTER_TREE_LINK_ID = "master-tree-link-id"
  val PAYLOAD = "payload"
  val SIGNATURE = "signature"
  val DEVICE_ID = "device-id"
  val UPP_CHAIN = "upp-chain"
  val HASH = "hash"
  val PREV_HASH = "prev_hash"
  val TYPE = "type"
  val ETHEREUM_TESTNET_RINKEBY_TESTNET_NETWORK = "ETHEREUM_TESTNET_RINKEBY_TESTNET_NETWORK"
  val UBIRCH = "ubirch"
  val CATEGORY_LABEL = "CATEGORY"
  val NAME_LABEL = "NAME"
  val ENCODER_SYSTEM = "ENCODER"
  val DISPATCHER_SYSTEM = "DISPATCHER"
  val EVENT_LOG_SYSTEM = "EVENT_LOG"
  val SUCCESS = "success"
  val FAILURE = "failure"

}
