@startuml

object Consumer <<singleton>> #DDDD11

object TreeCreatorExecutor <<executor>> #DDDDDD
object FilterExecutor <<executor>> #DDDDDD
object EventLogsParser <<executor>> #DDDDDD
object Commit <<executor>> #DDDDDD
object TreeEventLogCreation <<executor>> #DDDDDD


object TreeCreator #add8e6
object TreeEventLogCreator #add8e6
object TreeCache #add8e6
object TreePublisher #add8e6
object TreeCreationTrigger #add8e6
object TreUpgrade #add8e6
object TreeMonitor #ff4000
object InstantMonitor
object TreeWarmup #add8e6

Consumer -> FilterExecutor : sends CRs and filters
TreeMonitor <-- FilterExecutor: checks basic tree
FilterExecutor -> EventLogsParser
EventLogsParser -> TreeCreatorExecutor
TreeCreator --> TreeCache: stores latest root hash
TreeCreatorExecutor --> TreeMonitor: creates/splits trees
TreeCreatorExecutor -> TreeEventLogCreation
TreeMonitor --> TreeCreator: creates/splits trees
TreeEventLogCreation --> TreeMonitor: creates tree event logs
TreeEventLogCreation -> Commit
TreeMonitor <-- Commit: publishes
TreeMonitor --> TreeWarmup: makes sure BigBangTree and Latest Tree are properly set
TreeMonitor --> TreeEventLogCreator: creates tree event logs
TreeMonitor --> TreePublisher : publishes
TreeMonitor --> TreeCreationTrigger: Checks treeMinSize and treeEvery
TreeMonitor --> TreUpgrade : Upgrades trees
TreUpgrade -->  InstantMonitor
TreeCreationTrigger -->  InstantMonitor

@enduml

