# Default values for event-log-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ubirch/event-log-service
  tag: 20190201-dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9042

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
