apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-log-service
  namespace: prometheus
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: event-log-service
  endpoints:
  - port: prometheus-monitor
